package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.Person;

/**
 * Class _Agronomist was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Agronomist extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> PLANTS_PLANTED = new Property<Integer>("plantsPlanted");
    public static final Property<Person> PERSON = new Property<Person>("person");

    public void setPlantsPlanted(int plantsPlanted) {
        writeProperty("plantsPlanted", plantsPlanted);
    }
    public int getPlantsPlanted() {
        Object value = readProperty("plantsPlanted");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPerson(Person person) {
        setToOneTarget("person", person, true);
    }

    public Person getPerson() {
        return (Person)readProperty("person");
    }


}
