package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvDocument;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvPerson;

/**
 * Class _IvBirthCertificate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvBirthCertificate extends IvDocument {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> DOCTOR = new Property<String>("doctor");
    public static final Property<IvPerson> PERSON = new Property<IvPerson>("person");

    public void setDoctor(String doctor) {
        writeProperty("doctor", doctor);
    }
    public String getDoctor() {
        return (String)readProperty("doctor");
    }

    public void setPerson(IvPerson person) {
        setToOneTarget("person", person, true);
    }

    public IvPerson getPerson() {
        return (IvPerson)readProperty("person");
    }


}
