package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvDocument;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvWorkplace;

/**
 * Class _IvDeed was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvDeed extends IvDocument {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<IvWorkplace> WORKPLACE = new Property<IvWorkplace>("workplace");

    public void setWorkplace(IvWorkplace workplace) {
        setToOneTarget("workplace", workplace, true);
    }

    public IvWorkplace getWorkplace() {
        return (IvWorkplace)readProperty("workplace");
    }


}
