package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvEntity;

/**
 * Class _IvEmail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvEmail extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ADDRESS = new Property<String>("address");
    public static final Property<IvEntity> ENTITY = new Property<IvEntity>("entity");

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setEntity(IvEntity entity) {
        setToOneTarget("entity", entity, true);
    }

    public IvEntity getEntity() {
        return (IvEntity)readProperty("entity");
    }


}
