package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvEmail;

/**
 * Class _IvEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> REFERENCE = new Property<String>("reference");
    public static final Property<String> TYPE = new Property<String>("type");
    public static final Property<List<IvEmail>> EMAILS = new Property<List<IvEmail>>("emails");

    public void setReference(String reference) {
        writeProperty("reference", reference);
    }
    public String getReference() {
        return (String)readProperty("reference");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void addToEmails(IvEmail obj) {
        addToManyTarget("emails", obj, true);
    }
    public void removeFromEmails(IvEmail obj) {
        removeToManyTarget("emails", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<IvEmail> getEmails() {
        return (List<IvEmail>)readProperty("emails");
    }


}
