package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvAgronomist;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvDocument;

/**
 * Class _IvOrder was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvOrder extends IvDocument {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ORDER_TYPE = new Property<String>("orderType");
    public static final Property<IvAgronomist> AGRONOMIST = new Property<IvAgronomist>("agronomist");

    public void setOrderType(String orderType) {
        writeProperty("orderType", orderType);
    }
    public String getOrderType() {
        return (String)readProperty("orderType");
    }

    public void setAgronomist(IvAgronomist agronomist) {
        setToOneTarget("agronomist", agronomist, true);
    }

    public IvAgronomist getAgronomist() {
        return (IvAgronomist)readProperty("agronomist");
    }


}
