package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvAgronomist;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvDriversLicense;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvEntity;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvFamily;

/**
 * Class _IvPerson was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvPerson extends IvEntity {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<IvAgronomist> AGRONOMIST = new Property<IvAgronomist>("agronomist");
    public static final Property<IvDriversLicense> DRIVERS_LICENSE = new Property<IvDriversLicense>("driversLicense");
    public static final Property<IvFamily> FAMILY = new Property<IvFamily>("family");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setAgronomist(IvAgronomist agronomist) {
        setToOneTarget("agronomist", agronomist, true);
    }

    public IvAgronomist getAgronomist() {
        return (IvAgronomist)readProperty("agronomist");
    }


    public void setDriversLicense(IvDriversLicense driversLicense) {
        setToOneTarget("driversLicense", driversLicense, true);
    }

    public IvDriversLicense getDriversLicense() {
        return (IvDriversLicense)readProperty("driversLicense");
    }


    public void setFamily(IvFamily family) {
        setToOneTarget("family", family, true);
    }

    public IvFamily getFamily() {
        return (IvFamily)readProperty("family");
    }


}
