package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvOrder;

/**
 * Class _IvPurchaseOrder was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvPurchaseOrder extends IvOrder {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> TOTAL = new Property<Integer>("total");

    public void setTotal(int total) {
        writeProperty("total", total);
    }
    public int getTotal() {
        Object value = readProperty("total");
        return (value != null) ? (Integer) value : 0;
    }

}
