package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvDocument;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvPerson;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvSalesOrder;

/**
 * Class _IvReceipt was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvReceipt extends IvDocument {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> TOTAL = new Property<Integer>("total");
    public static final Property<IvPerson> PERSON = new Property<IvPerson>("person");
    public static final Property<IvSalesOrder> SALES_ORDER = new Property<IvSalesOrder>("salesOrder");

    public void setTotal(int total) {
        writeProperty("total", total);
    }
    public int getTotal() {
        Object value = readProperty("total");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPerson(IvPerson person) {
        setToOneTarget("person", person, true);
    }

    public IvPerson getPerson() {
        return (IvPerson)readProperty("person");
    }


    public void setSalesOrder(IvSalesOrder salesOrder) {
        setToOneTarget("salesOrder", salesOrder, true);
    }

    public IvSalesOrder getSalesOrder() {
        return (IvSalesOrder)readProperty("salesOrder");
    }


}
