package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvOrder;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvPerson;
import org.apache.cayenne.testdo.inheritance_vertical_sb.IvReceipt;

/**
 * Class _IvSalesOrder was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvSalesOrder extends IvOrder {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> TOTAL = new Property<Integer>("total");
    public static final Property<IvPerson> PERSON = new Property<IvPerson>("person");
    public static final Property<IvReceipt> RECEIPT = new Property<IvReceipt>("receipt");

    public void setTotal(int total) {
        writeProperty("total", total);
    }
    public int getTotal() {
        Object value = readProperty("total");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPerson(IvPerson person) {
        setToOneTarget("person", person, true);
    }

    public IvPerson getPerson() {
        return (IvPerson)readProperty("person");
    }


    public void setReceipt(IvReceipt receipt) {
        setToOneTarget("receipt", receipt, true);
    }

    public IvReceipt getReceipt() {
        return (IvReceipt)readProperty("receipt");
    }


}
