package org.apache.cayenne.testdo.inheritance_vertical_sb.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical_sb.Agronomist;
import org.apache.cayenne.testdo.inheritance_vertical_sb.DriversLicense;
import org.apache.cayenne.testdo.inheritance_vertical_sb.Entity;
import org.apache.cayenne.testdo.inheritance_vertical_sb.Family;

/**
 * Class _Person was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Person extends Entity {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<Agronomist> AGRONOMIST = new Property<Agronomist>("agronomist");
    public static final Property<DriversLicense> DRIVERS_LICENSE = new Property<DriversLicense>("driversLicense");
    public static final Property<Family> FAMILY = new Property<Family>("family");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setAgronomist(Agronomist agronomist) {
        setToOneTarget("agronomist", agronomist, true);
    }

    public Agronomist getAgronomist() {
        return (Agronomist)readProperty("agronomist");
    }


    public void setDriversLicense(DriversLicense driversLicense) {
        setToOneTarget("driversLicense", driversLicense, true);
    }

    public DriversLicense getDriversLicense() {
        return (DriversLicense)readProperty("driversLicense");
    }


    public void setFamily(Family family) {
        setToOneTarget("family", family, true);
    }

    public Family getFamily() {
        return (Family)readProperty("family");
    }


}
