package org.apache.cayenne.testdo.inheritance_vertical.auto;

import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical.IvColor;
import org.apache.cayenne.testdo.inheritance_vertical.IvShape;

import java.util.List;

/**
 * Class _IvConcrete was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvCircle extends IvShape {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Integer> RADIUS = new Property<Integer>("radius");
    public static final Property<List<IvColor>> COLORS_USING_DEFAULT = new Property<List<IvColor>>("colorsUsingDefault");

    public void setRadius(Integer radius) {
        writeProperty("radius", radius);
    }
    public Integer getRadius() {
        return (Integer)readProperty("radius");
    }

    public void addToColorsUsingDefault(IvColor obj) {
        addToManyTarget("colorsUsingDefault", obj, true);
    }
    public void removeFromColorsUsingDefault(IvColor obj) {
        removeToManyTarget("colorsUsingDefault", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<IvColor> getColorsUsingDefault() {
        return (List<IvColor>)readProperty("colorsUsingDefault");
    }

}
