package org.apache.cayenne.testdo.inheritance_vertical.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical.IvImpl;
import org.apache.cayenne.testdo.inheritance_vertical.IvSquare;

import java.util.List;

/**
 * Class _IvConcrete was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvOther extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<IvImpl>> IMPLS = new Property<List<IvImpl>>("impls");
    public static final Property<List<IvSquare>> SQUARES = new Property<List<IvSquare>>("squares");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToImpls(IvImpl obj) {
        addToManyTarget("impls", obj, true);
    }
    public void removeFromImpls(IvImpl obj) {
        removeToManyTarget("impls", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<IvImpl> getImpls() {
        return (List<IvImpl>)readProperty("impls");
    }

    public void addToSquares(IvSquare obj) {
        addToManyTarget("squares", obj, true);
    }
    public void removeFromSquares(IvSquare obj) {
        removeToManyTarget("squares", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<IvSquare> getSquares() {
        return (List<IvSquare>)readProperty("squares");
    }

}
