package org.apache.cayenne.testdo.inheritance_vertical.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.apache.cayenne.testdo.inheritance_vertical.IvColor;
import org.apache.cayenne.testdo.inheritance_vertical.IvShape;
import org.apache.cayenne.testdo.inheritance_vertical.IvStudent;

import java.util.List;

/**
 * Class _IvAbstract was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IvShape extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> TYPE = new Property<String>("type");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<IvColor> COLOR = new Property<IvColor>("color");
    public static final Property<List<IvStudent>> STUDENTS_WHO_FAVOR = new Property<List<IvStudent>>("studentsWhoFavor");

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setColor(IvColor color) {
        writeProperty("color", color);
    }
    public IvColor getColor() {
        return (IvColor)readProperty("color");
    }

    public void addToStudentsWhoFavor(IvStudent obj) {
        addToManyTarget("studentsWhoFavor", obj, true);
    }
    public void removeFromStudentsWhoFavor(IvStudent obj) {
        removeToManyTarget("studentsWhoFavor", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<IvStudent> getStudentsWhoFavor() {
        return (List<IvStudent>)readProperty("studentsWhoFavor");
    }

}
